### ISSUE TITLE
Wrong datetime

### ISSUE THREAD

**Issue by tologonkudaiberdiuulu** [SebastienBtr/Dash-Chat-2#85] opened 2024-02-21 16:52 UTC
Hi. Thank you for your package. I have a problem

![telegram-cloud-photo-size-2-5382103933746533531-y](https://github.com/SebastienBtr/Dash-Chat-2/assets/47391827/0e11a424-81d1-4dc3-900e-42fa9c851bac)

In the picture above, I've created chat 22:43. But in chat you can see it's 16:23. Is there something with package or I should give time zone somehow?

**Comment by SebastienBtr** [comment] 2024-03-08 14:22
I don't see anything wrong with DashChat package, it is just showing the date using the DateTime you give to the Message. You should check in which format/timezone your dates are saved in your database and how you fetch them. Seems like you have an issue with your date not being converted in UTC or Local when you "speak" with your database.

I'm closing it since the issue isn't related to the package as far as I know, but let me know in case you need more help

**Closed as completed by SebastienBtr** 2024-03-08 14:22 UTC
Labels: question

**Comment by K-isikoglu** [comment] 2025-07-30 06:04
If you're talking about having the correct timestamp on every single message, try setting messageOptions in DashChat constructor:
`messageOptions: const MessageOptions(showTime: true)`
