### ISSUE TITLE
message list shifted up if extendBodyBehindAppBar is true

### ISSUE THREAD

**Issue by Trennum** [SebastienBtr/Dash-Chat-2#44] opened 2023-04-06 21:28 UTC
When I set the extendBodyBehindAppBar parameter to true all the messages in the message list are moved up. They should not shift up and should stay in place the same way they are when extendBodyBehindAppBar is false.

[stackoverflow link](https://stackoverflow.com/questions/75953879/dash-chat-2-message-list-shifted-up-if-extendbodybehindappbar-is-true)

The entire bug with screen shots and code samples are posted on stackoverflow.

**Comment by LegendAF** [comment] 2023-05-10 23:57
Can you replicate this with the [Dash-Chat-2 example](https://github.com/SebastienBtr/Dash-Chat-2/tree/main/example)? I was unable to see what your screenshots are showing. I even copied your code directly into one of the examples (without `GetBuilder` surrounding Dash Chat) and I don't see it.

**Comment by Trennum** [comment] 2023-05-11 00:22
<img width="372" alt="Screenshot 2023-05-10 at 5 21 19 PM" src="https://github.com/SebastienBtr/Dash-Chat-2/assets/68714458/acf6f655-92db-4ea8-9d14-40082774e4f9">
<img width="364" alt="Screenshot 2023-05-10 at 5 21 38 PM" src="https://github.com/SebastienBtr/Dash-Chat-2/assets/68714458/40cc2b94-44cf-4aca-afbf-f9684ee6dbc0">

**Comment by Trennum** [comment] 2023-05-11 00:25
Left is extendBodyBehindAppBar: true and the right is extendBodyBehindAppBar: false. You can see how the bottom is pushed up when it is true. I have also removed GetBuilder for this example (show in screenshots above) and the code is running only as the child in the Expanded widget still producing this layout issue.

Flutter 3.7.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 90c64ed42b (7 weeks ago) • 2023-03-21 11:27:08 -0500
Engine • revision 9aa7816315
Tools • Dart 2.19.5 • DevTools 2.20.1
dash_chat_2: ^0.0.15

**Comment by Trennum** [comment] 2023-05-11 00:27
`return Container(
      decoration: const BoxDecoration(
        color: Colors.black,
        image: DecorationImage(
          image: AssetImage('assets/images/bg_chat_invert.jpg'),
          fit: BoxFit.cover,
        ),
      ),
      child: Scaffold(
        backgroundColor: Colors.transparent,
        appBar: AppBar(
          backgroundColor: Colors.transparent,
          title: _buildHeader(channelMessagesController),
          // leading: BackButton(
          //   onPressed: () => _channelMessagesController.closePage(),
          // ),
          //elevation: 0.0,
        ),
        extendBodyBehindAppBar: false,
        extendBody: true,
        body: Padding(
          padding: const EdgeInsets.fromLTRB(10, 0, 10, 14),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                child: DashChat(
                  currentUser: channelMessagesController.chatSender,
                  onSend: (ChatMessage m) {
                    _sendMessage(context, channelMessagesController);
                  },
                  messages: channelMessagesController.messages,
                  inputOptions: InputOptions(
                    textController: channelMessagesController.inputTextController,
                    inputTextStyle: const TextStyle(color: Colors.black),
                    sendButtonBuilder: defaultSendButton(color: palette.kButtonColor!),
                  ),
                ),
                // child: GetBuilder<ChannelMessagesPageController>(
                //   tag: uid.toString(),
                //   builder: (controller) {
                //     return DashChat(
                //       currentUser: channelMessagesController.chatSender,
                //       onSend: (ChatMessage m) {
                //         _sendMessage(context, channelMessagesController);
                //       },
                //       messages: channelMessagesController.messages,
                //       inputOptions: InputOptions(
                //         textController: channelMessagesController.inputTextController,
                //         inputTextStyle: const TextStyle(color: Colors.black),
                //         sendButtonBuilder: defaultSendButton(color: palette.kButtonColor!),
                //       ),
                //     );
                //   },
                // ),
              ),
            ],
          ),
        ),
      ),
    );`

**Comment by LegendAF** [comment] 2023-05-11 06:47
Thank you for the test code. I was not able to reproduce this on a physical iPhone 14 Pro or on the simulator using the same device. Here are some videos.

Simulator:

https://github.com/SebastienBtr/Dash-Chat-2/assets/825344/1221745a-7506-423e-9df0-16c9c13321fd

Physical:

https://github.com/SebastienBtr/Dash-Chat-2/assets/825344/053416ca-fa6a-4650-b087-1fc7a16d5439

Here is the code I ended up using because when I copy + pasted yours I was missing some functions.

```
import 'package:dash_chat_2/dash_chat_2.dart';
import 'package:examples/data.dart';
import 'package:flutter/material.dart';

class Basic extends StatefulWidget {
  @override
  State<Basic> createState() => BasicState();
}

class BasicState extends State<Basic> {
  List<ChatMessage> messages = basicSample;

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        color: Colors.black,
        image: DecorationImage(
          image: AssetImage('assets/images/bg_chat_invert.jpg'),
          fit: BoxFit.cover,
        ),
      ),
      child: Scaffold(
        backgroundColor: Colors.transparent,
        appBar: AppBar(
          backgroundColor: Colors.transparent,
          title: Text('Test'),
          // leading: BackButton(
          //   onPressed: () => _channelMessagesController.closePage(),
          // ),
          //elevation: 0.0,
        ),
        extendBodyBehindAppBar:
            false, //****Toggle this between true and false to reproduce the issue ****///
        extendBody: true,
        body: Padding(
          padding: const EdgeInsets.fromLTRB(10, 0, 10, 14),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                child: DashChat(
                  currentUser: user,
                  onSend: (ChatMessage m) {
                    setState(() {
                      messages.insert(0, m);
                    });
                  },
                  messages: messages,
                  inputOptions: InputOptions(
                    inputTextStyle: const TextStyle(color: Colors.black),
                  ),
                ),
                // child: GetBuilder<ChannelMessagesPageController>(
                //   tag: uid.toString(),
                //   builder: (controller) {
                //     return DashChat(
                //       currentUser: channelMessagesController.chatSender,
                //       onSend: (ChatMessage m) {
                //         _sendMessage(context, channelMessagesController);
                //       },
                //       messages: channelMessagesController.messages,
                //       inputOptions: InputOptions(
                //         textController: channelMessagesController.inputTextController,
                //         inputTextStyle: const TextStyle(color: Colors.black),
                //         sendButtonBuilder: defaultSendButton(color: palette.kButtonColor!),
                //       ),
                //     );
                //   },
                // ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
I am curious what the disconnect could be between what I am seeing and what you are seeing. 🤔

**Comment by LegendAF** [comment] 2023-05-11 07:16
Curious as to what it looks like in the app we are developing, it seemingly works with no issue as well. 😭 

![image](https://github.com/SebastienBtr/Dash-Chat-2/assets/825344/683e0b0d-439c-4c8c-9c65-e3058f160298)

**Comment by Trennum** [comment] 2023-05-11 19:17
Hey guys. Thanks for continuing to look at this. So I can repro it with Basic.  I took the code from basic (above) and created the following StatefulWidget (code below) and am still having the same problem. My next step is to create a clean project and only add DashChat as a dependency and see what happens. 

```
import 'package:dash_chat_2/dash_chat_2.dart';
import 'package:flutter/material.dart';

class Basic extends StatefulWidget {
  const Basic({super.key});

  @override
  State<Basic> createState() => BasicState();
}

class BasicState extends State<Basic> {
  List<ChatMessage> messages = [
    ChatMessage(
      text: 'Hello Venom',
      user: ChatUser(id: '1', firstName: 'Peter', lastName: 'Parker'),
      createdAt: DateTime.now(),
    ),
    ChatMessage(
      text: 'Hello Spiderman',
      user: ChatUser(id: '1', firstName: 'Eddie', lastName: 'Brock'),
      createdAt: DateTime.now(),
    ),
    ChatMessage(
      text: 'I know you tried to steal my girl you punk',
      user: ChatUser(id: '1', firstName: 'Peter', lastName: 'Parker'),
      createdAt: DateTime.now(),
    ),
    ChatMessage(
      text: 'She\'s so fine and totally digs my black tights',
      user: ChatUser(id: '1', firstName: 'Eddie', lastName: 'Brock'),
      createdAt: DateTime.now(),
    ),
    ChatMessage(
      text:
          'blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda',
      user: ChatUser(id: '1', firstName: 'Peter', lastName: 'Parker'),
      createdAt: DateTime.now(),
    ),
    ChatMessage(
      text:
          'blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda blah da da blah blah yadda yadda yadda yadda',
      user: ChatUser(id: '1', firstName: 'Eddie', lastName: 'Brock'),
      createdAt: DateTime.now(),
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        color: Colors.black,
        image: DecorationImage(
          image: AssetImage('assets/images/bg_chat_invert.jpg'),
          fit: BoxFit.cover,
        ),
      ),
      child: Scaffold(
        backgroundColor: Colors.transparent,
        appBar: AppBar(
          backgroundColor: Colors.transparent,
          title: const Text('Test'),          
        ),
        extendBodyBehindAppBar: true, //****Toggle this between true and false to reproduce the issue ****///
        extendBody: true,
        body: Padding(
          padding: const EdgeInsets.fromLTRB(10, 0, 10, 14),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Expanded(
                child: DashChat(
                  currentUser: ChatUser(id: '1', firstName: 'Peter', lastName: 'Parker'),
                  onSend: (ChatMessage m) {
                    setState(() {
                      messages.insert(0, m);
                    });
                  },
                  messages: messages,
                  inputOptions: const InputOptions(
                    inputTextStyle: TextStyle(color: Colors.black),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

```

**Comment by Trennum** [comment] 2023-05-11 19:46
Not super thrilled to report this but a clean project with only DashChat added does not reproduce the issue. It works as expected. Not sure what would be causing this? If you have any suggests or ideas please share otherwise it looks like I'll start off by adding all my dependencies back in and seeing if that has anything to do with it. Thank you again for your time and attention and if/when I figure this out I'll report back on this thread with my findings. Thanks again.

**Comment by SebastienBtr** [comment] 2023-05-12 08:48
`Not sure what would be causing this`
Yes really strange, I'll close the issue but don't hesitate to comment here if you find out what was your issue

**Closed by SebastienBtr** 2023-05-12 08:48 UTC
Labels: bug
